
CREATE TABLE zz_data (
	id INTEGER AUTO_INCREMENT(1, 1) NOT NULL,
	title CHARACTER VARYING (300) DEFAULT '',
	url CHARACTER VARYING (300),
	[data_type] CHARACTER VARYING (100),
	source CHARACTER VARYING (100),
	content CHARACTER VARYING (1073741823) NOT NULL,
	hit_count INTEGER NOT NULL,
	pub_date DATETIME NOT NULL,
	col_date DATETIME NOT NULL,
	use_yn CHARACTER(1) NOT NULL,
	CONSTRAINT pk PRIMARY KEY(id)
)
COLLATE utf8_bin
REUSE_OID;

