

CREATE TABLE `ZZ_DATA` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	`TITLE` VARCHAR(300) NULL DEFAULT NULL COMMENT '제목' COLLATE 'utf8_unicode_ci',
	`URL` VARCHAR(300) NULL DEFAULT NULL COMMENT 'URL' COLLATE 'utf8_unicode_ci',
	`DATA_TYPE` VARCHAR(100) NULL DEFAULT NULL COMMENT '분류' COLLATE 'utf8_unicode_ci',
	`SOURCE` VARCHAR(100) NULL DEFAULT NULL COMMENT '출처' COLLATE 'utf8_unicode_ci',
	`CONTENT` TEXT NOT NULL COMMENT '내용' COLLATE 'utf8_unicode_ci',
	`HIT_COUNT` INT(11) NOT NULL COMMENT '조회수',
	`PUB_DATE` DATETIME NOT NULL COMMENT '게재일',
	`COL_DATE` DATETIME NOT NULL COMMENT '수집일',
	`USE_YN` CHAR(1) NOT NULL COMMENT '사용여부' COLLATE 'utf8_unicode_ci',
	INDEX `인덱스 1` (`ID`)
)
COMMENT='수집데이터'
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=2
;
