

CREATE TABLE ZZ_DATA 
(
  ID NUMBER(*, 0) NOT NULL 
, TITLE VARCHAR2(300 BYTE) 
, URL VARCHAR2(300 BYTE) 
, DATA_TYPE VARCHAR2(100 BYTE) 
, SOURCE VARCHAR2(100 BYTE) 
, CONTENT CLOB NOT NULL 
, HIT_COUNT NUMBER(*, 0) NOT NULL 
, PUB_DATE DATE NOT NULL 
, COL_DATE DATE NOT NULL 
, USE_YN CHAR(1 BYTE) NOT NULL 
, CONSTRAINT ZZ_DATA_PK PRIMARY KEY 
  (
    ID 
  )  
);

COMMENT ON COLUMN ZZ_DATA.ID IS 'ID';
COMMENT ON COLUMN ZZ_DATA.TITLE IS '제목';
COMMENT ON COLUMN ZZ_DATA.URL IS 'URL';
COMMENT ON COLUMN ZZ_DATA.DATA_TYPE IS '분류';
COMMENT ON COLUMN ZZ_DATA.SOURCE IS '출처';
COMMENT ON COLUMN ZZ_DATA.CONTENT IS '내용';
COMMENT ON COLUMN ZZ_DATA.HIT_COUNT IS '조회수';
COMMENT ON COLUMN ZZ_DATA.PUB_DATE IS '게재일';
COMMENT ON COLUMN ZZ_DATA.COL_DATE IS '수집일';
COMMENT ON COLUMN ZZ_DATA.USE_YN IS '사용여부';


CREATE SEQUENCE ZZ_DATA_ID_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCYCLE;
